mailer_example/config/routes.rb
MailerExample::Application.routes.draw do
  get "users/new"
  get "project/home"

    root 'project#home'

  

end

mailer_example/app/models/user.rb
class User < ActiveRecord::Base
end

mailer_example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

mailer_example/app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def home
  end
end

mailer_example/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.first
    UserMailer.welcome_email(@user).deliver
  end
end

mailer_example/app/helpers/application_helper.rb
module ApplicationHelper
end

mailer_example/app/helpers/project_helper.rb
module ProjectHelper
end

mailer_example/app/helpers/users_helper.rb
module UsersHelper
end

mailer_example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailerExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

mailer_example/app/views/project/home.html.erb
<h1>Mailer Examples</h1>


Send Email:

<%= link_to "Send Email", users_new_path %>

mailer_example/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<p><%=@user.name%>, <%=@user.email%></p>